from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
FRONTEND_DIR = ROOT_DIR / "frontend"
ASSETS_DIR = ROOT_DIR / "assets"
DIST_WEB_DIR = ROOT_DIR / "dist" / "web"


def reset_dist() -> None:
    if DIST_WEB_DIR.exists():
        shutil.rmtree(DIST_WEB_DIR)
    DIST_WEB_DIR.mkdir(parents=True, exist_ok=True)


def build_index_html() -> None:
    src = FRONTEND_DIR / "index.html"
    content = src.read_text(encoding="utf-8")
    content = content.replace("../assets/", "./assets/")
    (DIST_WEB_DIR / "index.html").write_text(content, encoding="utf-8")


def build_runtime_config(require_api_base_url: bool = False) -> None:
    api_base = os.getenv("GEOQR_API_BASE_URL", "").strip().rstrip("/")
    if require_api_base_url and not api_base:
        raise RuntimeError(
            "GEOQR_API_BASE_URL is required for mobile build. "
            "Example: set GEOQR_API_BASE_URL=https://your-backend-domain"
        )
    generated = (
        "// Generated by scripts/build_web.py\n"
        "window.APP_CONFIG = {\n"
        f'  API_BASE_URL: "{api_base}",\n'
        "};\n"
    )
    (DIST_WEB_DIR / "config.js").write_text(generated, encoding="utf-8")


def copy_static_files() -> None:
    shutil.copy2(FRONTEND_DIR / "app.js", DIST_WEB_DIR / "app.js")
    shutil.copy2(FRONTEND_DIR / "styles.css", DIST_WEB_DIR / "styles.css")
    shutil.copytree(ASSETS_DIR, DIST_WEB_DIR / "assets", dirs_exist_ok=True)


def main() -> None:
    require_api_base_url = "--require-api-base-url" in sys.argv[1:]
    reset_dist()
    build_index_html()
    build_runtime_config(require_api_base_url=require_api_base_url)
    copy_static_files()
    print(f"Built web assets at: {DIST_WEB_DIR}")


if __name__ == "__main__":
    main()
